name: Pull Request Check
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

concurrency:
  group: pr-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Dry Run Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dryRun --branches ${{ steps.branch-name.outputs.current_branch }}
